# Generated by Django 5.1.3 on 2024-11-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('team1', models.CharField(max_length=256, verbose_name='Команда 1')),
                ('team2', models.CharField(max_length=256, verbose_name='Команда 2')),
                ('score1', models.IntegerField(verbose_name='Счёт 1')),
                ('score2', models.IntegerField(verbose_name='Счёт 2')),
                ('place', models.CharField(max_length=256, verbose_name='Место проведения')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
